/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppAbout {}
  interface AppBlog {
    'years': any;
  }
  interface AppHome {}
  interface AppRoot {
    'posts': any;
  }
  interface ArmMigration {}
  interface BioContent {}
  interface FirstPost {}
  interface GitSetup {}
  interface HomePosts {
    'posts': any;
  }
  interface NavBar {}
  interface ProjectList {}
}

declare global {


  interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {}
  var HTMLAppAboutElement: {
    prototype: HTMLAppAboutElement;
    new (): HTMLAppAboutElement;
  };

  interface HTMLAppBlogElement extends Components.AppBlog, HTMLStencilElement {}
  var HTMLAppBlogElement: {
    prototype: HTMLAppBlogElement;
    new (): HTMLAppBlogElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLArmMigrationElement extends Components.ArmMigration, HTMLStencilElement {}
  var HTMLArmMigrationElement: {
    prototype: HTMLArmMigrationElement;
    new (): HTMLArmMigrationElement;
  };

  interface HTMLBioContentElement extends Components.BioContent, HTMLStencilElement {}
  var HTMLBioContentElement: {
    prototype: HTMLBioContentElement;
    new (): HTMLBioContentElement;
  };

  interface HTMLFirstPostElement extends Components.FirstPost, HTMLStencilElement {}
  var HTMLFirstPostElement: {
    prototype: HTMLFirstPostElement;
    new (): HTMLFirstPostElement;
  };

  interface HTMLGitSetupElement extends Components.GitSetup, HTMLStencilElement {}
  var HTMLGitSetupElement: {
    prototype: HTMLGitSetupElement;
    new (): HTMLGitSetupElement;
  };

  interface HTMLHomePostsElement extends Components.HomePosts, HTMLStencilElement {}
  var HTMLHomePostsElement: {
    prototype: HTMLHomePostsElement;
    new (): HTMLHomePostsElement;
  };

  interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {}
  var HTMLNavBarElement: {
    prototype: HTMLNavBarElement;
    new (): HTMLNavBarElement;
  };

  interface HTMLProjectListElement extends Components.ProjectList, HTMLStencilElement {}
  var HTMLProjectListElement: {
    prototype: HTMLProjectListElement;
    new (): HTMLProjectListElement;
  };
  interface HTMLElementTagNameMap {
    'app-about': HTMLAppAboutElement;
    'app-blog': HTMLAppBlogElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'arm-migration': HTMLArmMigrationElement;
    'bio-content': HTMLBioContentElement;
    'first-post': HTMLFirstPostElement;
    'git-setup': HTMLGitSetupElement;
    'home-posts': HTMLHomePostsElement;
    'nav-bar': HTMLNavBarElement;
    'project-list': HTMLProjectListElement;
  }
}

declare namespace LocalJSX {
  interface AppAbout {}
  interface AppBlog {
    'years'?: any;
  }
  interface AppHome {}
  interface AppRoot {
    'posts'?: any;
  }
  interface ArmMigration {}
  interface BioContent {}
  interface FirstPost {}
  interface GitSetup {}
  interface HomePosts {
    'posts'?: any;
  }
  interface NavBar {}
  interface ProjectList {}

  interface IntrinsicElements {
    'app-about': AppAbout;
    'app-blog': AppBlog;
    'app-home': AppHome;
    'app-root': AppRoot;
    'arm-migration': ArmMigration;
    'bio-content': BioContent;
    'first-post': FirstPost;
    'git-setup': GitSetup;
    'home-posts': HomePosts;
    'nav-bar': NavBar;
    'project-list': ProjectList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-about': LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
      'app-blog': LocalJSX.AppBlog & JSXBase.HTMLAttributes<HTMLAppBlogElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'arm-migration': LocalJSX.ArmMigration & JSXBase.HTMLAttributes<HTMLArmMigrationElement>;
      'bio-content': LocalJSX.BioContent & JSXBase.HTMLAttributes<HTMLBioContentElement>;
      'first-post': LocalJSX.FirstPost & JSXBase.HTMLAttributes<HTMLFirstPostElement>;
      'git-setup': LocalJSX.GitSetup & JSXBase.HTMLAttributes<HTMLGitSetupElement>;
      'home-posts': LocalJSX.HomePosts & JSXBase.HTMLAttributes<HTMLHomePostsElement>;
      'nav-bar': LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
      'project-list': LocalJSX.ProjectList & JSXBase.HTMLAttributes<HTMLProjectListElement>;
    }
  }
}


